version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs/
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5443:5432"
    restart: always
    hostname: ${POSTGRES_HOST}

volumes:
  app:
    driver: local
  pgdata:
    driver: local
